AWSTemplateFormatVersion: 2010-09-09
Description: hello stack
Parameters:
  DeploymentBucket:
    Type: String
Resources:
  HelloLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/hello
  IamRoleLambdaExecution:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: hello-lambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                Resource:
                  - !Sub >-
                    arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/hello:*
              - Effect: Allow
                Action:
                  - 'logs:PutLogEvents'
                Resource:
                  - !Sub >-
                    arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/hello:*:*
      Path: /
      RoleName: hello-lambda
  HelloLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref  DeploymentBucket
        S3Key: demo/hello.zip
      FunctionName: hello
      Handler: handler.hello
      MemorySize: 1024
      Role: !GetAtt
        - IamRoleLambdaExecution
        - Arn
      Runtime: nodejs6.10
      Timeout: 6
      Environment:
        Variables:
          SAY_HELLO_TO: erbody
    DependsOn:
      - HelloLogGroup
      - IamRoleLambdaExecution
  ApiGatewayRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: demo
  ApiGatewayResourceWhateverVar:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt
        - ApiGatewayRestApi
        - RootResourceId
      PathPart: '{whatever}'
      RestApiId: !Ref ApiGatewayRestApi
  ApiGatewayMethodWhateverVarGet:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: GET
      RequestParameters: {}
      ResourceId: !Ref ApiGatewayResourceWhateverVar
      RestApiId: !Ref ApiGatewayRestApi
      ApiKeyRequired: true
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        Uri: !Join
          - ''
          - - 'arn:aws:apigateway:'
            - !Ref 'AWS::Region'
            - ':lambda:path/2015-03-31/functions/'
            - !GetAtt
              - HelloLambdaFunction
              - Arn
            - /invocations
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: '{ "whatever" : "$input.params(''whatever'')" }'
        IntegrationResponses:
          - StatusCode: 200
            SelectionPattern: ''
            ResponseParameters: {}
            ResponseTemplates: {}
      MethodResponses:
        - ResponseParameters: {}
          ResponseModels: {}
          StatusCode: 200
  ApiGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      StageName: demo
    DependsOn:
      - ApiGatewayMethodWhateverVarGet
  ApiGatewayApiKey1:
    Type: 'AWS::ApiGateway::ApiKey'
    Properties:
      Enabled: true
      Name: internal
      StageKeys:
        - RestApiId: !Ref ApiGatewayRestApi
          StageName: demo
    DependsOn: ApiGatewayDeployment
  ApiGatewayUsagePlan:
    Type: 'AWS::ApiGateway::UsagePlan'
    DependsOn: ApiGatewayDeployment
    Properties:
      ApiStages:
        - ApiId: !Ref ApiGatewayRestApi
          Stage: demo
      UsagePlanName: demo
  ApiGatewayUsagePlanKey1:
    Type: 'AWS::ApiGateway::UsagePlanKey'
    Properties:
      KeyId: !Ref ApiGatewayApiKey1
      KeyType: API_KEY
      UsagePlanId: !Ref ApiGatewayUsagePlan
  HelloLambdaPermissionApiGateway:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt
        - HelloLambdaFunction
        - Arn
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - !Ref ApiGatewayRestApi
          - /*/*
Outputs:
  ServiceEndpoint:
    Description: URL of the service endpoint
    Value: !Join
      - ''
      - - 'https://'
        - !Ref ApiGatewayRestApi
        - .execute-api.us-east-1.amazonaws.com/demo

